l_german:
  IMPTOCK2DISPLAYNAME: "von Imperator zu Crusader Kings II"
  IMPERATOR: "Imperator"
  CK2GAME: "Crusader Kings II"
  CK2FOLDER: "Crusader Kings II-Installationsverzeichnis"
  CK2FOLDERTIP: "Der Pfad auf Ihrem Computer, auf dem Crusader Kings II installiert ist"
  CK2MOD: "Crusader Kings II Mod-Verzeichnis"
  CK2MODTIP: "Der Pfad auf Ihrem Computer, auf dem Crusader Kings II Mods speichert"
  IMPERATORFOLDER: "Imperator-Installationsverzeichnis"
  IMPERATORFOLDERTIP: "Der Pfad auf Ihrem Computer, auf dem Imperator installiert ist"
  IMPERATORMOD: "Imperator Mod-Verzeichnis"
  IMPERATORMODTIP: "Der Pfad auf Ihrem Computer, auf dem Imperator Mods speichert"
  IMPERATORFILE: "Pfad zur ausf√ºhrbaren Datei des Konverters"
  IMPERATORFILETIP: "Pfad zu Converter.jar"
  IMPERATORSAVE: "Pfad zum Imperator-Savegame"
  IMPERATORSAVETIP: "Pfad zu Ihrem Savegame von Imperator"
