l_french:
 IMPTOCK2DISPLAYNAME: "de Imperator à Crusader Kings II"
 IMPERATOR: "Imperator"
 CK2GAME: "Crusader Kings II"
 CK2FOLDER: "Répertoire d'installation de Crusader Kings II"
 CK2FOLDERTIP: "Le chemin sur votre ordinateur où Crusader Kings II est installé"
 CK2MOD: "Répertoire des mods Crusader Kings II"
 CK2MODTIP: "Le chemin sur votre ordinateur où Crusader Kings II stocke les mods"
 IMPERATORFOLDER: "Répertoire d'installation d'Imperator"
 IMPERATORFOLDERTIP: "Le chemin sur votre ordinateur où Imperator est installé"
 IMPERATORMOD: "Répertoire des mods Imperator"
 IMPERATORMODTIP: "Le chemin sur votre ordinateur où Imperator stocke les mods"
 IMPERATORFILE: "Chemin vers l'exécutable du convertisseur"
 IMPERATORFILETIP: "Chemin vers Converter.jar"
 IMPERATORSAVE: "Chemin vers la sauvegarde Imperator"
 IMPERATORSAVETIP: "Chemin vers votre sauvegarde de Imperator"
