l_latin:
  CK2DISPLAYNAME: "ex Imperator ad Crusader Kings II"
  IMPERATOR: "Imperator"
  CK2GAME: "Crusader Kings II"
  CK2FOLDER: "Scapus locationis Crusader Kings II"
  CK2FOLDERTIP: "Via in qua locatus est ludus Crusader Kings II"
  CK2MOD: "Scapus correctionum Crusader Kings II"
  CK2MODTIP: "Via in qua locatae sunt correctiones Crusader Kings II"
  IMPERATORFOLDER: "Scapus locationis Imperator"
  IMPERATORFOLDERTIP: "Via in qua locatus est ludus Imperator"
  IMPERATORMOD: "Scapus correctionum Imperator"
  IMPERATORMODTIP: "Via in qua locatae sunt correctiones Imperator"
  IMPERATORFILE: "Via programmatis"
  IMPERATORFILETIP: "Via ad Converter.jar"
  IMPERATORSAVE: "Via ad conditum Imperator"
  IMPERATORSAVETIP: "Via ad conditum Imperator"
