l_italian:
  IMPTOCK2DISPLAYNAME: "da Imperator a Crusader Kings II"
  IMPERATOR: "Imperator"
  CK2GAME: "Crusader Kings II"
  CK2FOLDER: "Cartella di installazione di Crusader Kings II"
  CK2FOLDERTIP: "Il percorso in cui è installato Crusader Kings II"
  CK2MOD: "Cartella delle mod per Crusader Kings II"
  CK2MODTIP: "Il percorso in cui Crusader Kings II memorizza le mod"
  IMPERATORFOLDER: "Cartella di installazione di Imperator"
  IMPERATORFOLDERTIP: "Il percorso in cui è installato Imperator"
  IMPERATORMOD: "Cartella delle mod per Imperator"
  IMPERATORMODTIP: "Il percorso in cui Imperator memorizza le mod"
  IMPERATORFILE: "Percorso dell'eseguibile del convertitore"
  IMPERATORFILETIP: "Percorso di Converter.jar"
  IMPERATORSAVE: "Percorso del savegame Imperator"
  IMPERATORSAVETIP: "Percorso per il tuo savegame da Imperator"
